apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
      version: blue
  template:
    metadata:
      labels:
        app: ecommerce
        version: blue
    spec:
      containers:
        - name: ecommerce
          image: sweetyraj22/ecommerce:blue
          ports:
            - containerPort: 80
