apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce
    version: blue   # change this to green when switching versions
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080     # you can choose any free port between 30000–32767
  type: NodePort
