apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce
    version: blue   # start with blue version
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # must be between 30000–32767
  type: NodePort

