apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  selector:
    app: ecommerce
    version: blue   # initially points to blue
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
